50 generation order fix
skku-amang/backend pull request #51
Opened 2024-10-26 15:44 UTC by nhjbest22

#50 
Fixed issue with handling GET requests for the Generation model

change leader property(ForeignKey of CustomUser) into writable

After Merging #44 

You can test Generation by using following command
`docker compose exec backend python manage.py test core.tests.test_generation`

2024-10-26 16:55 UTC, manamana32321 requested changes

2024-10-26 16:55 UTC, manamana32321 commented on core/views/generation.py
> +            raise Http404("Invalid Generation ID")
`django.http`의 에러는 Django Rest Framework가 아니라 Django 자체 템플릿 엔진을 위한 에러 클래스 입니다.
`rest_framework.exceptions`의 에러 클래스를 사용해주세요.
본 경우에는 `NotFound`로 대체 가능합니다.

하지만 문맥상 ID가 없는 것(404)이 아니라 잘못된(400) ID이기에
`BadRequest` 에러 클래스가 적절해 보입니다.

2024-10-26 16:55 UTC, manamana32321 commented on core/views/generation.py
> +        except Exception:
전체 예외 처리는 매우 위험합니다.
`Decimal` 변환 과정에서 발생 가능한 에러 클래스에 대해서만 처리가 필요합니다.

2024-10-26 16:55 UTC, manamana32321 commented on core/views/generation.py
> +            raise Http404("Generation not found")
이 또한 DRF의 에러 클래스로 변경해주세요.

그리고 이 코드들은 충분히 self-explained 하기에 주석을 생략해도 좋아 보입니다.

2024-10-26 17:55 UTC, nhjbest22 commented on core/views/generation.py
> +            raise Http404("Invalid Generation ID")
[FIXED]
https://github.com/skku-amang/backend/pull/51/commits/0f88a48869fc9b05fc3dac019463180a3f540a8b

2024-10-26 17:55 UTC, nhjbest22 commented on core/views/generation.py
> +        except Exception:
[FIXED]
https://github.com/skku-amang/backend/pull/51/commits/0f88a48869fc9b05fc3dac019463180a3f540a8b

2024-10-26 17:55 UTC, nhjbest22 commented on core/views/generation.py
> +            raise Http404("Generation not found")
[FIXED]
https://github.com/skku-amang/backend/pull/51/commits/0f88a48869fc9b05fc3dac019463180a3f540a8b

2024-10-27 10:34 UTC, manamana32321 approved these changes
LGTM

2024-10-27 11:14 UTC, merged